server:
  port: 8091

spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://db:5432/schedule
  application:
    name: notification-service

mybatis:
  configuration:
    map-underscore-to-camel-case: true
