server:
  port: 8090

spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://db:5432/schedule
  application:
    name: task-service

mybatis:
  configuration:
    map-underscore-to-camel-case: true
